language: node_js
node_js:
  - 'stable'
cache: yarn
deploy:
  provider: pages
  skip-cleanup: false
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: false
  on:
    branch: master
branches:
  only:
    - master
before_script:
  - 'yarn global add gatsby'
script:
  - 'yarn run build:prod'
after_success:
  - 'yarn run deploy'
